#!/bin/bash

set -e

# shellcheck disable=SC1091
[ -f .env ] && . .env

[ ! -d node_modules ] && npm ci

scripts/kill-ganache-cli

# use node_url value from env
if [ -n "$NODE_URL" ]; then
    node_url=$NODE_URL
fi

# use mnemonic value from env
if [ -n "$MNEMONIC" ]; then
    mnemonic=$MNEMONIC
fi

# caller script will pass --quiet param as $2
npx ganache-cli --fork "$node_url" --host 0.0.0.0 --mnemonic "$mnemonic" -e 10000 --quiet &
